[package]
name = "implementation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfdx = "0.10.0"
jpeg-decoder = "0.3.0"
rand = "0.8.5"
show-image = {version = "0.13.1", features = ["save"]}
